spring.application.name=spai

spring.ai.openai.api-key=keyid


spring.datasource.url=jdbc:mysql://localhost:3306/springai?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.ai.chat.memory.repository.jdbc.initialize-schema=never	-- 자동으로 테이블을 만들지 안도록 설정
