plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springAiVersion', "1.1.5")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'	// JPA 설정
	implementation 'org.springframework.boot:spring-boot-starter-mustache'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.ai:spring-ai-starter-model-openai'
	implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'		// Spring AI에서 기본적으로 JDBC방식 구현체를 제공하지 않기 때문에 Spring AI의 chat-memory-repository-jdbc 요소를 추가해야함
	implementation 'org.springframework.ai:spring-ai-advisors-vector-store'	// api에 특정 db의 정보, 임베딩 api의 정보 등을 추가해주는 어댑터
	implementation 'org.springframework.ai:spring-ai-starter-vector-store-elasticsearch'	// elasticsearch DB 
	implementation 'co.elastic.clients:elasticsearch-java:8.17.2'	// 자기의 elasticsearch에 맞는 버전 작성
	implementation 'org.springframework.ai:spring-ai-markdown-document-reader'	// Extract: Reader 구현체를 위한 의존성 추가
	implementation 'org.springframework.ai:spring-ai-pdf-document-reader'
	implementation 'org.springframework.ai:spring-ai-tika-document-reader'
	runtimeOnly 'com.mysql:mysql-connector-j'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
